"use client"

import Background from '@/components/Background/Background'
import './globals.css'
import type { Metadata } from 'next'
import { useRef } from 'react';
import Header from '../components/header/index';
import StickyCursor from '../components/stickyCursor/index';



// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const stickyElement = useRef(null);
  return (
    <html lang="en">
      <body >
        <Background/>
        <Header ref={stickyElement}/>
        <StickyCursor stickyElement={stickyElement}/>
        {children}
        </body>
    </html>
  )
}
